#\u670D\u52A1\u540D\u79F0
spring:
  application:
    name: micr-dataservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ylb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: gao123456

#\u8BBE\u7F6Emybatis
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#dubbo\u914D\u7F6E
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.bjpowernode.dataservice.service
  provider:
    timeout: 50000
    retries: 0

# 密码的盐
ylb:
  config:
    password-salt: asldglkzm1akjsh23dkfaskjnkja113q
